# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

connectTimeout: Optional[int]
"""
Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
"""

password: Optional[str]
"""
Password to authenticate with Infoblox server.
"""

poolConnections: Optional[int]
"""
Maximum number of connections to establish to the Infoblox server. Zero means unlimited.
"""

port: Optional[str]
"""
Port number used for connection for Infoblox Server.
"""

server: Optional[str]
"""
Infoblox server IP address.
"""

sslmode: Optional[bool]
"""
If set, Infoblox client will permit unverifiable SSL certificates.
"""

username: Optional[str]
"""
User to authenticate with Infoblox server.
"""

wapiVersion: Optional[str]
"""
WAPI Version of Infoblox server defaults to v2.7.
"""

