// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./a";
export * from "./aaaa";
export * from "./cname";

// Import resources to register:
import { A } from "./a";
import { AAAA } from "./aaaa";
import { CName } from "./cname";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "infoblox:record/a:A":
                return new A(name, <any>undefined, { urn })
            case "infoblox:record/aAAA:AAAA":
                return new AAAA(name, <any>undefined, { urn })
            case "infoblox:record/cName:CName":
                return new CName(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("infoblox", "record/a", _module)
pulumi.runtime.registerResourceModule("infoblox", "record/aAAA", _module)
pulumi.runtime.registerResourceModule("infoblox", "record/cName", _module)
