// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export * from "./allocation";
export * from "./association";
export * from "./network";
export * from "./networkContainer";

// Import resources to register:
import { Allocation } from "./allocation";
import { Association } from "./association";
import { Network } from "./network";
import { NetworkContainer } from "./networkContainer";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "infoblox:ipv4/allocation:Allocation":
                return new Allocation(name, <any>undefined, { urn })
            case "infoblox:ipv4/association:Association":
                return new Association(name, <any>undefined, { urn })
            case "infoblox:ipv4/network:Network":
                return new Network(name, <any>undefined, { urn })
            case "infoblox:ipv4/networkContainer:NetworkContainer":
                return new NetworkContainer(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("infoblox", "ipv4/allocation", _module)
pulumi.runtime.registerResourceModule("infoblox", "ipv4/association", _module)
pulumi.runtime.registerResourceModule("infoblox", "ipv4/network", _module)
pulumi.runtime.registerResourceModule("infoblox", "ipv4/networkContainer", _module)
