// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class NetworkContainer extends pulumi.CustomResource {
    /**
     * Get an existing NetworkContainer resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkContainerState, opts?: pulumi.CustomResourceOptions): NetworkContainer {
        return new NetworkContainer(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infoblox:ipv4/networkContainer:NetworkContainer';

    /**
     * Returns true if the given object is an instance of NetworkContainer.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkContainer {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkContainer.__pulumiType;
    }

    /**
     * The network container's address, in CIDR format.
     */
    public readonly cidr!: pulumi.Output<string>;
    /**
     * A description of the network container.
     */
    public readonly comment!: pulumi.Output<string | undefined>;
    /**
     * The Extensible attributes of the network container to be added/updated, as a map in JSON format
     */
    public readonly extAttrs!: pulumi.Output<string | undefined>;
    /**
     * The name of network view for the network container.
     */
    public readonly networkView!: pulumi.Output<string | undefined>;

    /**
     * Create a NetworkContainer resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkContainerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkContainerArgs | NetworkContainerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkContainerState | undefined;
            resourceInputs["cidr"] = state ? state.cidr : undefined;
            resourceInputs["comment"] = state ? state.comment : undefined;
            resourceInputs["extAttrs"] = state ? state.extAttrs : undefined;
            resourceInputs["networkView"] = state ? state.networkView : undefined;
        } else {
            const args = argsOrState as NetworkContainerArgs | undefined;
            if ((!args || args.cidr === undefined) && !opts.urn) {
                throw new Error("Missing required property 'cidr'");
            }
            resourceInputs["cidr"] = args ? args.cidr : undefined;
            resourceInputs["comment"] = args ? args.comment : undefined;
            resourceInputs["extAttrs"] = args ? args.extAttrs : undefined;
            resourceInputs["networkView"] = args ? args.networkView : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkContainer.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NetworkContainer resources.
 */
export interface NetworkContainerState {
    /**
     * The network container's address, in CIDR format.
     */
    cidr?: pulumi.Input<string>;
    /**
     * A description of the network container.
     */
    comment?: pulumi.Input<string>;
    /**
     * The Extensible attributes of the network container to be added/updated, as a map in JSON format
     */
    extAttrs?: pulumi.Input<string>;
    /**
     * The name of network view for the network container.
     */
    networkView?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NetworkContainer resource.
 */
export interface NetworkContainerArgs {
    /**
     * The network container's address, in CIDR format.
     */
    cidr: pulumi.Input<string>;
    /**
     * A description of the network container.
     */
    comment?: pulumi.Input<string>;
    /**
     * The Extensible attributes of the network container to be added/updated, as a map in JSON format
     */
    extAttrs?: pulumi.Input<string>;
    /**
     * The name of network view for the network container.
     */
    networkView?: pulumi.Input<string>;
}
